### ISSUE TITLE
Add Disney+

### ISSUE THREAD

**Issue by criticalsession** [CharlieS1103/hide-hulu-menu-bar#1]
Hey,

Would love to add Disney+ to the mix. 

First time contributing to a git project so would like to try the pull myself if that's okay (just to have gone through the entire process)?

**Comment by criticalsession** [comment]
I've completed the changes for this issue here: #2 . I don't know how to automatically assign it to the issue though so it closes when the merge is done (or if I can do it myself), sorry.

**Comment by CharlieS1103** [comment]
@criticalsession Thanks!
